name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout gh-pages branch
        run: |
          git fetch --all --prune
          git checkout gh-pages
          git pull --rebase origin main

      - name: Build project
        run: npm run build

      - name: Move dist files
        run: mv ./dist ./

      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"

      - name: Push changes
        run: git push origin gh-pages
